[package]
name = "test-prompts"
version = "0.1.0"
edition = "2021"

[dependencies]
clap = { version = "4.0.28", features = ["derive"] }
dialoguer = { version = "0.10.2", features = ["fuzzy-select"] }
